/**
 * Maritime Identification Digits (MID) to country mapping.
 * Source: ITU Table of Maritime Identification Digits
 * https://www.itu.int/en/ITU-R/terrestrial/fmd/Pages/mid.aspx
 *
 * Maps the first 3 digits of an MMSI to country code (ISO 3166-1 alpha-2)
 * and country name. Covers naval/military-relevant nations.
 */

interface MIDEntry {
  country: string;
  code: string; // ISO 3166-1 alpha-2
}

const MID_TABLE: Record<number, MIDEntry> = {
  // Europe
  201: { country: "Albania", code: "AL" },
  202: { country: "Andorra", code: "AD" },
  203: { country: "Austria", code: "AT" },
  204: { country: "Portugal (Azores)", code: "PT" },
  205: { country: "Belgium", code: "BE" },
  206: { country: "Belarus", code: "BY" },
  207: { country: "Bulgaria", code: "BG" },
  208: { country: "Vatican", code: "VA" },
  209: { country: "Cyprus", code: "CY" },
  210: { country: "Cyprus", code: "CY" },
  211: { country: "Germany", code: "DE" },
  212: { country: "Cyprus", code: "CY" },
  213: { country: "Georgia", code: "GE" },
  214: { country: "Moldova", code: "MD" },
  215: { country: "Malta", code: "MT" },
  216: { country: "Armenia", code: "AM" },
  218: { country: "Germany", code: "DE" },
  219: { country: "Denmark", code: "DK" },
  220: { country: "Denmark", code: "DK" },
  224: { country: "Spain", code: "ES" },
  225: { country: "Spain", code: "ES" },
  226: { country: "France", code: "FR" },
  227: { country: "France", code: "FR" },
  228: { country: "France", code: "FR" },
  229: { country: "Malta", code: "MT" },
  230: { country: "Finland", code: "FI" },
  231: { country: "Denmark (Faroe Islands)", code: "FO" },
  232: { country: "United Kingdom", code: "GB" },
  233: { country: "United Kingdom", code: "GB" },
  234: { country: "United Kingdom", code: "GB" },
  235: { country: "United Kingdom", code: "GB" },
  236: { country: "Gibraltar", code: "GI" },
  237: { country: "Greece", code: "GR" },
  238: { country: "Croatia", code: "HR" },
  239: { country: "Greece", code: "GR" },
  240: { country: "Greece", code: "GR" },
  241: { country: "Greece", code: "GR" },
  242: { country: "Morocco", code: "MA" },
  243: { country: "Hungary", code: "HU" },
  244: { country: "Netherlands", code: "NL" },
  245: { country: "Netherlands", code: "NL" },
  246: { country: "Netherlands", code: "NL" },
  247: { country: "Italy", code: "IT" },
  248: { country: "Malta", code: "MT" },
  249: { country: "Malta", code: "MT" },
  250: { country: "Ireland", code: "IE" },
  251: { country: "Iceland", code: "IS" },
  252: { country: "Liechtenstein", code: "LI" },
  253: { country: "Luxembourg", code: "LU" },
  254: { country: "Monaco", code: "MC" },
  255: { country: "Portugal (Madeira)", code: "PT" },
  256: { country: "Malta", code: "MT" },
  257: { country: "Norway", code: "NO" },
  258: { country: "Norway", code: "NO" },
  259: { country: "Norway", code: "NO" },
  261: { country: "Poland", code: "PL" },
  263: { country: "Portugal", code: "PT" },
  264: { country: "Romania", code: "RO" },
  265: { country: "Sweden", code: "SE" },
  266: { country: "Sweden", code: "SE" },
  267: { country: "Slovakia", code: "SK" },
  268: { country: "San Marino", code: "SM" },
  269: { country: "Switzerland", code: "CH" },
  270: { country: "Czech Republic", code: "CZ" },
  271: { country: "Turkey", code: "TR" },
  272: { country: "Ukraine", code: "UA" },
  273: { country: "Russia", code: "RU" },
  274: { country: "North Macedonia", code: "MK" },
  275: { country: "Latvia", code: "LV" },
  276: { country: "Estonia", code: "EE" },
  277: { country: "Lithuania", code: "LT" },
  278: { country: "Slovenia", code: "SI" },
  279: { country: "Serbia", code: "RS" },

  // North America
  303: { country: "Alaska (USA)", code: "US" },
  304: { country: "Antigua and Barbuda", code: "AG" },
  305: { country: "Antigua and Barbuda", code: "AG" },
  306: { country: "Netherlands Antilles", code: "AN" },
  307: { country: "Aruba", code: "AW" },
  308: { country: "Bahamas", code: "BS" },
  309: { country: "Bahamas", code: "BS" },
  310: { country: "Bermuda", code: "BM" },
  311: { country: "Bahamas", code: "BS" },
  312: { country: "Belize", code: "BZ" },
  314: { country: "Barbados", code: "BB" },
  316: { country: "Canada", code: "CA" },
  319: { country: "Cayman Islands", code: "KY" },
  321: { country: "Costa Rica", code: "CR" },
  323: { country: "Cuba", code: "CU" },
  325: { country: "Dominica", code: "DM" },
  327: { country: "Dominican Republic", code: "DO" },
  329: { country: "Guadeloupe", code: "GP" },
  330: { country: "Grenada", code: "GD" },
  331: { country: "Greenland", code: "GL" },
  332: { country: "Guatemala", code: "GT" },
  334: { country: "Honduras", code: "HN" },
  336: { country: "Haiti", code: "HT" },
  338: { country: "USA", code: "US" },
  339: { country: "Jamaica", code: "JM" },
  341: { country: "Saint Kitts and Nevis", code: "KN" },
  343: { country: "Saint Lucia", code: "LC" },
  345: { country: "Mexico", code: "MX" },
  347: { country: "Martinique", code: "MQ" },
  348: { country: "Montserrat", code: "MS" },
  350: { country: "Nicaragua", code: "NI" },
  351: { country: "Panama", code: "PA" },
  352: { country: "Panama", code: "PA" },
  353: { country: "Panama", code: "PA" },
  354: { country: "Panama", code: "PA" },
  355: { country: "Panama", code: "PA" },
  356: { country: "Panama", code: "PA" },
  357: { country: "Panama", code: "PA" },
  358: { country: "Puerto Rico", code: "PR" },
  359: { country: "El Salvador", code: "SV" },
  361: { country: "Saint Pierre and Miquelon", code: "PM" },
  362: { country: "Trinidad and Tobago", code: "TT" },
  364: { country: "Turks and Caicos", code: "TC" },
  366: { country: "USA", code: "US" },
  367: { country: "USA", code: "US" },
  368: { country: "USA", code: "US" },
  369: { country: "USA", code: "US" },
  370: { country: "Panama", code: "PA" },
  371: { country: "Panama", code: "PA" },
  372: { country: "Panama", code: "PA" },
  373: { country: "Panama", code: "PA" },
  374: { country: "Panama", code: "PA" },
  375: { country: "Saint Vincent and Grenadines", code: "VC" },
  376: { country: "Saint Vincent and Grenadines", code: "VC" },
  377: { country: "Saint Vincent and Grenadines", code: "VC" },
  378: { country: "British Virgin Islands", code: "VG" },
  379: { country: "US Virgin Islands", code: "VI" },

  // Asia
  401: { country: "Afghanistan", code: "AF" },
  403: { country: "Saudi Arabia", code: "SA" },
  405: { country: "Bangladesh", code: "BD" },
  408: { country: "Bahrain", code: "BH" },
  410: { country: "Bhutan", code: "BT" },
  412: { country: "China", code: "CN" },
  413: { country: "China", code: "CN" },
  414: { country: "China", code: "CN" },
  416: { country: "Taiwan", code: "TW" },
  417: { country: "Sri Lanka", code: "LK" },
  419: { country: "India", code: "IN" },
  422: { country: "Iran", code: "IR" },
  423: { country: "Azerbaijan", code: "AZ" },
  425: { country: "Iraq", code: "IQ" },
  428: { country: "Israel", code: "IL" },
  431: { country: "Japan", code: "JP" },
  432: { country: "Japan", code: "JP" },
  434: { country: "Turkmenistan", code: "TM" },
  436: { country: "Kazakhstan", code: "KZ" },
  437: { country: "Uzbekistan", code: "UZ" },
  438: { country: "Jordan", code: "JO" },
  440: { country: "South Korea", code: "KR" },
  441: { country: "South Korea", code: "KR" },
  443: { country: "Palestine", code: "PS" },
  445: { country: "North Korea", code: "KP" },
  447: { country: "Kuwait", code: "KW" },
  450: { country: "Lebanon", code: "LB" },
  451: { country: "Kyrgyzstan", code: "KG" },
  453: { country: "Macao", code: "MO" },
  455: { country: "Maldives", code: "MV" },
  457: { country: "Mongolia", code: "MN" },
  459: { country: "Nepal", code: "NP" },
  461: { country: "Oman", code: "OM" },
  463: { country: "Pakistan", code: "PK" },
  466: { country: "Qatar", code: "QA" },
  468: { country: "Syria", code: "SY" },
  470: { country: "UAE", code: "AE" },
  471: { country: "UAE", code: "AE" },
  472: { country: "Tajikistan", code: "TJ" },
  473: { country: "Yemen", code: "YE" },
  475: { country: "Thailand", code: "TH" },
  477: { country: "Hong Kong", code: "HK" },
  478: { country: "Bosnia and Herzegovina", code: "BA" },

  // Africa
  501: { country: "Antarctica (France)", code: "AQ" },
  503: { country: "Australia", code: "AU" },
  506: { country: "Myanmar", code: "MM" },
  508: { country: "Brunei", code: "BN" },
  510: { country: "Micronesia", code: "FM" },
  511: { country: "Palau", code: "PW" },
  512: { country: "New Zealand", code: "NZ" },
  514: { country: "Cambodia", code: "KH" },
  515: { country: "Cambodia", code: "KH" },
  516: { country: "Christmas Island", code: "CX" },
  518: { country: "Cook Islands", code: "CK" },
  520: { country: "Fiji", code: "FJ" },
  523: { country: "Cocos Islands", code: "CC" },
  525: { country: "Indonesia", code: "ID" },
  529: { country: "Kiribati", code: "KI" },
  531: { country: "Laos", code: "LA" },
  533: { country: "Malaysia", code: "MY" },
  536: { country: "Northern Mariana Islands", code: "MP" },
  538: { country: "Marshall Islands", code: "MH" },
  540: { country: "New Caledonia", code: "NC" },
  542: { country: "Niue", code: "NU" },
  544: { country: "Nauru", code: "NR" },
  546: { country: "French Polynesia", code: "PF" },
  548: { country: "Philippines", code: "PH" },
  553: { country: "Papua New Guinea", code: "PG" },
  555: { country: "Pitcairn Island", code: "PN" },
  557: { country: "Solomon Islands", code: "SB" },
  559: { country: "American Samoa", code: "AS" },
  561: { country: "Samoa", code: "WS" },
  563: { country: "Singapore", code: "SG" },
  564: { country: "Singapore", code: "SG" },
  565: { country: "Singapore", code: "SG" },
  566: { country: "Singapore", code: "SG" },
  567: { country: "Thailand", code: "TH" },
  570: { country: "Tonga", code: "TO" },
  572: { country: "Tuvalu", code: "TV" },
  574: { country: "Vietnam", code: "VN" },
  576: { country: "Vanuatu", code: "VU" },
  577: { country: "Vanuatu", code: "VU" },
  578: { country: "Wallis and Futuna", code: "WF" },

  // Africa
  601: { country: "South Africa", code: "ZA" },
  603: { country: "Angola", code: "AO" },
  605: { country: "Algeria", code: "DZ" },
  607: { country: "Saint Paul and Amsterdam Islands", code: "FR" },
  608: { country: "Ascension Island", code: "SH" },
  609: { country: "Burundi", code: "BI" },
  610: { country: "Benin", code: "BJ" },
  611: { country: "Botswana", code: "BW" },
  612: { country: "Central African Republic", code: "CF" },
  613: { country: "Cameroon", code: "CM" },
  615: { country: "Congo", code: "CG" },
  616: { country: "Comoros", code: "KM" },
  617: { country: "Cape Verde", code: "CV" },
  618: { country: "Crozet Archipelago", code: "FR" },
  619: { country: "Ivory Coast", code: "CI" },
  620: { country: "Comoros", code: "KM" },
  621: { country: "Djibouti", code: "DJ" },
  622: { country: "Egypt", code: "EG" },
  624: { country: "Ethiopia", code: "ET" },
  625: { country: "Eritrea", code: "ER" },
  626: { country: "Gabon", code: "GA" },
  627: { country: "Ghana", code: "GH" },
  629: { country: "Gambia", code: "GM" },
  630: { country: "Guinea-Bissau", code: "GW" },
  631: { country: "Equatorial Guinea", code: "GQ" },
  632: { country: "Guinea", code: "GN" },
  633: { country: "Burkina Faso", code: "BF" },
  634: { country: "Kenya", code: "KE" },
  635: { country: "Kerguelen Islands", code: "FR" },
  636: { country: "Liberia", code: "LR" },
  637: { country: "Liberia", code: "LR" },
  638: { country: "South Sudan", code: "SS" },
  642: { country: "Libya", code: "LY" },
  644: { country: "Lesotho", code: "LS" },
  645: { country: "Mauritius", code: "MU" },
  647: { country: "Madagascar", code: "MG" },
  649: { country: "Mali", code: "ML" },
  650: { country: "Mozambique", code: "MZ" },
  654: { country: "Mauritania", code: "MR" },
  655: { country: "Malawi", code: "MW" },
  656: { country: "Niger", code: "NE" },
  657: { country: "Nigeria", code: "NG" },
  659: { country: "Namibia", code: "NA" },
  660: { country: "Reunion", code: "RE" },
  661: { country: "Rwanda", code: "RW" },
  662: { country: "Sudan", code: "SD" },
  663: { country: "Senegal", code: "SN" },
  664: { country: "Seychelles", code: "SC" },
  665: { country: "Saint Helena", code: "SH" },
  666: { country: "Somalia", code: "SO" },
  667: { country: "Sierra Leone", code: "SL" },
  668: { country: "Sao Tome and Principe", code: "ST" },
  669: { country: "Eswatini", code: "SZ" },
  670: { country: "Chad", code: "TD" },
  671: { country: "Togo", code: "TG" },
  672: { country: "Tunisia", code: "TN" },
  674: { country: "Tanzania", code: "TZ" },
  675: { country: "Uganda", code: "UG" },
  676: { country: "DR Congo", code: "CD" },
  677: { country: "Tanzania", code: "TZ" },
  678: { country: "Zambia", code: "ZM" },
  679: { country: "Zimbabwe", code: "ZW" },

  // South America
  701: { country: "Argentina", code: "AR" },
  710: { country: "Brazil", code: "BR" },
  720: { country: "Bolivia", code: "BO" },
  725: { country: "Chile", code: "CL" },
  730: { country: "Colombia", code: "CO" },
  735: { country: "Ecuador", code: "EC" },
  740: { country: "Falkland Islands", code: "FK" },
  745: { country: "French Guiana", code: "GF" },
  750: { country: "Guyana", code: "GY" },
  755: { country: "Paraguay", code: "PY" },
  760: { country: "Peru", code: "PE" },
  765: { country: "Suriname", code: "SR" },
  770: { country: "Uruguay", code: "UY" },
  775: { country: "Venezuela", code: "VE" },
};

/**
 * Convert ISO 3166-1 alpha-2 country code to flag emoji.
 * Each letter is offset to the Regional Indicator Symbol range (U+1F1E6).
 */
function countryCodeToFlag(code: string): string {
  return [...code.toUpperCase()].map(
    (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65)
  ).join("");
}

export interface VesselCountry {
  country: string;
  code: string;
  flag: string;
}

/**
 * Decode the country from an MMSI number using the MID (first 3 digits).
 * Returns null if the MID is not recognized.
 */
export function getCountryFromMMSI(mmsi: number): VesselCountry | null {
  const mid = Math.floor(mmsi / 1000000);
  const entry = MID_TABLE[mid];
  if (!entry) return null;
  return {
    country: entry.country,
    code: entry.code,
    flag: countryCodeToFlag(entry.code),
  };
}

/**
 * Build a VesselFinder URL from an MMSI number.
 */
export function getVesselFinderUrl(mmsi: number): string {
  return `https://www.vesselfinder.com/vessels/details/${mmsi}`;
}
